# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eca371286d18d987951fecfd8c9bdce0dcdc64b5a472fdc0e9d96cc1f713f593e386b54ff2cb5a2915a66fd3a643d84a2b6bd0e3eb009d808f7023e8284ccb4

test:
  secret_key_base: 7b54c35a1a97d592dcda9cc24552c0e7da7a8dd440daf53b5b0b01248c9ac875857c35e931ab010bcd8e2458917160d7b399503c66f85548e3021b2b74bad030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
